[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
analyzer ={ path = "../analyzer" }
reporter ={ path = "../reporter" }
lexer ={ path = "../lexer" }
ast ={ path = "../ast" }
nyanc_core ={ path = "../core" }
parser ={ path = "../parser" }